# Generated by Django 4.2.1 on 2023-05-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Epics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epicsTitle', models.TextField(blank=True, null=True)),
                ('epicsImage', models.TextField(blank=True, null=True)),
                ('Address', models.TextField(blank=True, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
